### ISSUE TITLE
Package for Void linux

### ISSUE THREAD

**Issue by ghost** [xyproto/msg2#2]
> Makes `msg2` available to any distro, not just Arch Linux.

Now available on Void linux! :tada: 

https://github.com/void-linux/void-packages/commit/b4d9400f3811a646385e80a70883108b41ddc6f5

Best regards.

**Comment by xyproto** [comment]
Wow, that was unexpected, and nice. Thanks! :)

I just released 1.2.0 which is pretty much identical to 1.1.0, except that the text is bold instead of white, for even closer resemblance with the original `msg2` bash function in Arch Linux.

**Comment by xyproto** [comment]
I think Void Linux is up and coming, it's nice to see the package repository growing.

**Comment by ghost** [comment]
Updated!

https://github.com/void-linux/void-packages/commit/5ef7258f495c0c95402f44b815489c384881d121
